services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
